import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Search from "@/image/nav/Search.svg";
import { INavItem } from "./type/nav";
import ROUTES from "./routes";
import {
  AddPost,
  Clicked_Home_icon,
  Clicked_Search_Icon,
  Home_icon,
} from "@/image/nav/index";

import NavBar from "./components/NavBar";

import AuthContext from "@/context/AuthContext";
import SWRConfigContext from "@/context/SWRConfigContext";

const openSans = Open_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const listArray: INavItem[] = [
    {
      title: "홈",
      href: ROUTES.HOME.HOME,
      icon: <Home_icon />,
      clickedIcon: <Clicked_Home_icon />,
    },
    {
      title: "검색",
      href: ROUTES.SEARCH.HOME,
      icon: <Search />,
      clickedIcon: <Clicked_Search_Icon />,
    },
    {
      title: "탐색",
      href: ROUTES.POST.HOME,
      icon: <AddPost />,
      clickedIcon: <AddPost />,
    },
  ];
  return (
    <html className={openSans.className}>
      <body>
        <AuthContext>
          <NavBar />
          <main>
            <SWRConfigContext>
              <div id="portal"></div>
              {children}
            </SWRConfigContext>
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
